    <div class="page-header">
      <h1>Edit Photos</h1>
    </div>
    <form accept-charset="UTF-8" action="<?php echo $this->url(); ?>" class="form-vertical" id="formUpload" method="post" novalidate="novalidate">
      <fieldset>
        <div class="row">
          <div class="span6 control-group">
            <label class="control-label" for="name">Name:</label>
            <div class="controls">
              <?php echo $this->form->name ?>
            </div>
          </div>
          <div class="span6 control-group">
            <label class="control-label" for="email">e-mail:</label>
            <div class="controls">
              <?php echo $this->form->email ?>
            </div>
          </div>
        </div>
        <div class="control-group" id="uploader">
          <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
        </div>
        <?php echo $this->form->my_upload_count ?>
        <ul class="thumbnails" id="thumbnails">
          <input type="hidden" name="my_upload_count" value="<?php echo count($this->thumbnails) ?>" id="my_upload_count">
<?php foreach ($this->thumbnails as $thumb): ?>
          <li class="span2 <?php echo $thumb['id'] ?>">
            <div class="thumbnail">
              <input type="hidden" name="uploaded_<?php echo $thumb['i'] ?>_tmpname" value="<?php echo $thumb['uploaded_' . $thumb['i'] . '_tmpname'] ?>" />
              <input type="hidden" name="status_<?php echo $thumb['id'] ?>" value="<?php echo $thumb['status_' . $thumb['id']] ?>" />
              <input type="hidden" name="crop_<?php echo $thumb['id'] ?>" value="<?php echo $thumb['crop_' . $thumb['id']] ?>" />
              <img src="<?php echo $this->baseUrl('/files/' . $thumb['uploaded_' . $thumb['i'] . '_tmpname']) ?>" width="160" alt="" class="img_<?php echo $thumb['id'] ?>" />
              <div class="caption">
                <textarea name="caption_<?php echo $thumb['id'] ?>" class="my-caption hidden"><?php echo $thumb['caption_' . $thumb['id']] ?></textarea>
                <p><a href="#" class="btn btn-mini btn-info fn-crop">Crop</a> <a href="#" class="btn btn-mini btn-info fn-caption">Caption</a></p>
              </div>
            </div>
          </li>
<?php endforeach; ?>
        </ul>
<pre>
<?php print_r($this->thumbnails); ?>
</pre>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </fieldset>
    </form>
<script type="text/javascript">
<!--
LSLFileUpload({
  uploader: $("#uploader"),
  thumbnails: $('#thumbnails'),
  url: '<?php echo $this->url(array('action' => 'upload')); ?>',
  max_file_size: '10mb',
  max_file_count: 2,
  extensions: 'jpg,gif,png',
  base_url: '<?php echo $this->baseUrl() ?>',
  temp_dir: '<?php echo $this->baseUrl('/files/temp/') ?>',
  with_caption: true,
  with_crop: true,
  aspect_ratio: 4/3
});
-->
</script>
