    <div class="page-header">
      <h1>Edit Photos</h1>
    </div>
    <form accept-charset="UTF-8" action="<?php echo $this->url(); ?>" class="form-vertical" id="formUpload" method="post" novalidate="novalidate">
      <fieldset>
        <div class="row">
          <div class="span6 control-group">
            <label class="control-label" for="name">Name:</label>
            <div class="controls">
              <?php echo $this->form->name ?>
            </div>
          </div>
          <div class="span6 control-group">
            <label class="control-label" for="email">e-mail:</label>
            <div class="controls">
              <?php echo $this->form->email ?>
            </div>
          </div>
        </div>
        <div class="control-group" id="uploader">
          <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
        </div>
<?php echo $this->form->my_upload_count ?>
<?php echo $this->showFilesUploaded($this->thumbnails, array(
  'id'          => 'thumbnails',
  'isImage'     => true,
  'withCrop'    => true,
  'withCaption' => true
)); ?>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </fieldset>
    </form>
<script type="text/javascript">
<!--
LSLFileUpload({
  uploader: $("#uploader"),
  thumbnails: $('#thumbnails'),
  url: '<?php echo $this->url(array('action' => 'upload')); ?>',
  max_file_size: '10mb',
  max_file_count: 2,
  extensions: 'jpg,gif,png',
  base_url: '<?php echo $this->baseUrl() ?>',
  temp_dir: '<?php echo $this->baseUrl('/files/temp/') ?>',
  with_caption: true,
  with_crop: true,
  aspect_ratio: 4/3
});
-->
</script>
