    <div class="page-header">
      <h1>Send Photos</h1>
    </div>
    <form accept-charset="UTF-8" action="<?php echo $this->url(array('action' => 'create')); ?>" class="form-vertical" id="formUpload" method="post" novalidate="novalidate">
      <fieldset>
        <div class="row">
          <div class="span6 control-group">
            <label class="control-label" for="name">Name:</label>
            <div class="controls">
              <input type="text" class="span6" name="name" id="name" />
              <?php echo $this->form->name ?>
            </div>
          </div>
          <div class="span6 control-group">
            <label class="control-label" for="email">e-mail:</label>
            <div class="controls">
              <input type="text" class="span6" name="email" id="email" />
              <?php echo $this->form->email ?>
            </div>
          </div>
        </div>
        <div class="control-group" id="uploader">
          <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
        </div>
        <?php echo $this->form->uploader_count ?>
        <ul class="thumbnails" id="thumbnails">
        </ul>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </fieldset>
    </form>
<script type="text/javascript">
<!--
LSLFileUpload({
  uploader: $("#uploader"),
  thumbnails: $('#thumbnails'),
  url: '<?php echo $this->url(array('action' => 'upload')); ?>',
  max_file_size: '10mb',
  max_file_count: 2,
  extensions: 'jpg,gif,png',
  base_url: '<?php echo $this->baseUrl() ?>',
  temp_dir: '<?php echo $this->baseUrl('/files/temp/') ?>',
  with_caption: true,
  with_crop: true,
  aspect_ratio: 4/3
});
-->
</script>
